// <auto-generated />
using System;
using InventoryManagementSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250501172308_modifiedCheckConstraintForProductQuantity")]
    partial class modifiedCheckConstraintForProductQuantity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Product_Name");

                    b.HasIndex("Price")
                        .HasDatabaseName("IX_Product_Price");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Product_LowStockThreshold", "LowStockThreshold >= 0");

                            t.HasCheckConstraint("CK_Product_Price", "Price > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Description for Product A",
                            LowStockThreshold = 5,
                            Name = "Product A",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Description for Product B",
                            LowStockThreshold = 2,
                            Name = "Product B",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Description for Product C",
                            LowStockThreshold = 3,
                            Name = "Product C",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Description for Product D",
                            LowStockThreshold = 4,
                            Name = "Product D",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Description for Product E",
                            LowStockThreshold = 1,
                            Name = "Product E",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Description for Product F",
                            LowStockThreshold = 5,
                            Name = "Product F",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Description for Product G",
                            LowStockThreshold = 10,
                            Name = "Product G",
                            Price = 70.00m
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Description for Product H",
                            LowStockThreshold = 9,
                            Name = "Product H",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 9L,
                            Description = "Description for Product I",
                            LowStockThreshold = 11,
                            Name = "Product I",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 10L,
                            Description = "Description for Product J",
                            LowStockThreshold = 3,
                            Name = "Product J",
                            Price = 100.00m
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.ProductWarehouse", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "WarehouseId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ProductWarehouse", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductWarehouse_Quantity", "Quantity >= 0");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1L,
                            WarehouseId = 1L,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 2L,
                            WarehouseId = 1L,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 3L,
                            WarehouseId = 2L,
                            Quantity = 30
                        },
                        new
                        {
                            ProductId = 4L,
                            WarehouseId = 2L,
                            Quantity = 40
                        },
                        new
                        {
                            ProductId = 5L,
                            WarehouseId = 3L,
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("IX_Transaction_TransactionDate");

                    b.HasIndex("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_Transaction_TransactionType", "[TransactionType] IN (0, 1, 2)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ProductId = 1L,
                            Quantity = 5,
                            TransactionDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 0,
                            UserId = 1L,
                            WarehouseId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ProductId = 2L,
                            Quantity = 10,
                            TransactionDate = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 1,
                            UserId = 2L,
                            WarehouseId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            ProductId = 3L,
                            Quantity = 15,
                            TransactionDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 0,
                            UserId = 1L,
                            WarehouseId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            ProductId = 4L,
                            Quantity = 20,
                            TransactionDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 1,
                            UserId = 2L,
                            WarehouseId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            ProductId = 5L,
                            Quantity = 25,
                            TransactionDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 0,
                            UserId = 1L,
                            WarehouseId = 3L
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Email");

                    b.HasIndex("Username", "Password")
                        .HasDatabaseName("IX_User_Username_Password");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_Email", "Email LIKE '_%@_%._%'");

                            t.HasCheckConstraint("CK_User_Password", "LEN(Password) >= 6");

                            t.HasCheckConstraint("CK_User_Role", "Role IN (0, 1)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "email1@gmail.com",
                            Password = "Admin123$",
                            Role = 1,
                            Username = "Admin1"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "email2@gmail.com",
                            Password = "User123$",
                            Role = 0,
                            Username = "User1"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Warehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Warehouse A"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Warehouse B"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Warehouse C"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Infrastructure.Authentication.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.ProductWarehouse", b =>
                {
                    b.HasOne("InventoryManagementSystem.Domain.Entities.Product", "Product")
                        .WithMany("ProductWarehouse")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("ProductWarehouses")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("InventoryManagementSystem.Domain.Entities.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Transactions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductWarehouse");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("ProductWarehouses");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
